% !Rnw root = AABase.Rnw

\chapter{Key References}

\begin{flushright}
\texttt{In God We Trust; All Others Must Bring Data}

\emph{-- Willian Edwards Deming}
\end{flushright}

\vspace{12pt}


If you are new to R and data anaytics (or if it has been a while and you wish to refresh your mind), these are the key references you should start with:

\section{Beginner Level Resources}


\section{Intermediate Level Resources}


\section{Advanced Resources}

\chapterendsymbol